---
- include: deployer-user.yml

- name: install rsync
  apt: name=rsync state=present
  become: true
  become_user: root
  tags: server-provision

- block:
  - include: local-build.yml
    when: platform_client_deploy_src is not defined or not platform_client_deploy_src

  - name: ensure presence of source files at {{ platform_client_deploy_src }}
    local_action: stat path="{{ platform_client_deploy_src }}/index.html"
    register: src_index
  - fail: msg="missing source files at {{ platform_client_deploy_src }}"
    when: src_index.stat.isreg is not defined or not src_index.stat.isreg

  - name: ensure destination folder
    file: path={{ platform_client_docroot }} recurse=yes state=directory owner="{{ deploy_user }}" mode=0755

  - name: deploy by sync
    synchronize: src="{{ platform_client_deploy_src }}/" dest="{{ platform_client_docroot }}/"
    args:
      archive: no
      delete: yes
      recursive: yes
      owner: no
      rsync_opts: [ "--chmod=Dog+x,og+r" ]
      perms: yes
      times: yes
    become: true
    become_user: "{{ deploy_user }}"

  - name: copy config.js file to server
    template: src="templates/config.js.j2" dest={{ platform_client_docroot }}/config.js owner="{{ deploy_user }}"
    sudo: false

  - name: copy config.json file to server
    template: src="templates/config.json.j2" dest={{ platform_client_docroot }}/config.json owner="{{ deploy_user }}"
    sudo: false
  tags: code-deploy