---
- name: install rsync
  apt: name=rsync state=present
  sudo: true

- name: ensure presence of source files at {{ platform_client_deploy_src }}
  local_action: stat path="{{ platform_client_deploy_src }}/index.html"
  register: src_index
- fail: msg=missing source files at {{ platform_client_deploy_src }}
  when: src_index.stat.isreg is not defined or not src_index.stat.isreg

- name: ensure destination folder
  file: path={{ platform_client_base_path }}/{{ platform_client_static_folder }} state=directory

- name: deploy by sync
  synchronize: src="{{ platform_client_deploy_src }}/" dest="{{ platform_client_base_path }}/{{ platform_client_static_folder }}/"
  args:
    archive: no
    delete: yes
    recursive: yes
    perms: yes
    times: yes

- name: copy config.js file to server
  template: src="templates/config.js.j2" dest={{ platform_client_base_path }}/{{ platform_client_static_folder }}/config.js
  sudo: false