---
- block:
  - fail: msg="missing destination bucket name"
    when: not (platform_client_s3_dest_bucket|length)

  - name: ensure bucket accessibility for aws
    command: "{{ platform_client_aws_cli }} s3 ls s3://{{ platform_client_s3_dest_bucket }}"

  - name: ensure presence of source files
    stat: path="{{ platform_client_deploy_src }}/index.html"
    register: src_index

  - fail: msg="missing source files"
    when: src_index.stat.isreg is not defined or not src_index.stat.isreg

  - name: generate config.js file before sync to bucket
    template: src="templates/config.js.j2" dest={{ platform_client_deploy_src }}/config.js

  - name: generate config.json before sync to bucket
    template: src="templates/config.json.j2" dest={{ platform_client_deploy_src }}/config.json
    sudo: false

  - name: synchronize client contents to bucket
    command: "{{ platform_client_aws_cli }} s3 sync --delete {{ platform_client_deploy_src }} s3://{{ platform_client_s3_dest_bucket }}/{{ platform_client_s3_dest_prefix }}"

  environment:
    AWS_ACCESS_KEY_ID: "{{ platform_client_aws_access_key_id | default(lookup('env', 'AWS_ACCESS_KEY_ID')) }}"
    AWS_SECRET_ACCESS_KEY: "{{ platform_client_aws_secret_access_key | default(lookup('env', 'AWS_SECRET_ACCESS_KEY')) }}"
    AWS_DEFAULT_REGION: "{{ platform_client_aws_default_region | default(lookup('env', 'AWS_DEFAULT_REGION')) }}"
  delegate_to: 127.0.0.1
  tags: code-deploy
