---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: false
platforms:
  - name: ansible_platform_client_code_trusty
    image: ubuntu:trusty
    groups:
      - ansible_targets
  - name: ansible_platform_client_code_xenial
    image: ubuntu:xenial
    groups:
      - ansible_targets
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
